<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE roms [

<!ELEMENT roms ( rom+ ) >
<!ENTITY NL  "&#10;" ><!-- &NL; new line -->
<!ENTITY deg "&#176;" ><!-- &deg; degree sign -->
<!ENTITY micro  "&#181;" ><!-- micro sign -->

<!ELEMENT rom ( romid, table+ ) >
<!ATTLIST rom base CDATA #IMPLIED>

<!ELEMENT romid ( xmlid, internalidaddress, internalidstring, caseid?, ecuid, year, market, make, model, submodel, transmission, flashmethod?, memmodel, filesize, obsolete? ) >

<!ELEMENT xmlid (#PCDATA) >
<!ELEMENT internalidaddress (#PCDATA) >
<!ELEMENT internalidstring (#PCDATA) >
<!ELEMENT caseid (#PCDATA) >
<!ELEMENT ecuid (#PCDATA) >
<!ELEMENT year (#PCDATA) >
<!ELEMENT market (#PCDATA) >
<!ELEMENT make (#PCDATA) >
<!ELEMENT model (#PCDATA) >
<!ELEMENT submodel (#PCDATA) >
<!ELEMENT transmission (#PCDATA) >
<!ELEMENT flashmethod (#PCDATA) >
<!ELEMENT memmodel (#PCDATA) >
<!ELEMENT filesize (#PCDATA) >
<!ELEMENT obsolete (#PCDATA) >

<!ELEMENT table ( #PCDATA | scaling | table | description | data | state )* >
<!ATTLIST table
	type NMTOKENS #IMPLIED
	name CDATA #IMPLIED
	category CDATA #IMPLIED
	storagetype CDATA #IMPLIED
	endian (little | big) #IMPLIED
	sizex CDATA #IMPLIED
	sizey CDATA #IMPLIED
	userlevel (1 | 2 | 3 | 4 | 5) #IMPLIED
	logparam CDATA #IMPLIED
	storageaddress CDATA #IMPLIED >

<!ELEMENT scaling EMPTY >
<!ATTLIST scaling
	units CDATA #REQUIRED
	expression CDATA #REQUIRED
	to_byte CDATA #REQUIRED
	format CDATA #REQUIRED
	fineincrement CDATA #REQUIRED
	coarseincrement CDATA #REQUIRED >

<!ELEMENT description (#PCDATA) >

<!ELEMENT data (#PCDATA) >

<!ELEMENT state (#PCDATA) >
<!ATTLIST state
	name CDATA #REQUIRED
	data CDATA #REQUIRED >
]>
 <!--MS41 ECU DEFINITION FILE (VERSION 0.46.0) 2021-01-10 -->
 <!--TERMS, CONDITIONS, AND DISCLAIMERS
- - - - - - - - - - - - - - - - - - - - - - - - -
WARNING: These definition files are created as the result of the extremely complex and time consuming process of reverse-engineering the factory ECU. Because of this complexity, it is necessary to make certain assumptions and, therefore, it is impossible to always deal in absolutes in regards to representations made by these definitions. In addition, due to this complexity and the numerous variations among different ECUs, it is also impossible to guarantee that the definitions will not contain errors or other bugs. What this all means is that there is the potential for bugs, errors and misrepresentations which can result in damage to your motor, your ECU as well the possibility of causing your vehicle to behave unexpectedly on the road, increasing the risk of death or injury. Modifications to your vehicle's ECU may also be in violation of local, state and federal laws. By using these definition files, either directly or indirectly, you agree to assume 100% of all risk and RomRaider's creators and contributors shall not be held responsible for any damages or injuries you receive. This product is for advanced users only. There are no safeguards in place when tuning with RomRaider. As such, the potential for serious damage and injury still exists, even if the user does not experience any bugs or errors. As always, use at your own risk.

These definitions are created for FREE without any sort of guarantee. The developers cannot be held liable for any damage or injury incurred as a result of these definitions. USE AT YOUR OWN RISK!-->
<roms>

<rom> BMWMS41BASE 
<!-- v0.45
	- Added 7 tables for Accel Enrichment due to MAF
	- Added 2 tables that deal with Closed Loop - delay, AFR sensor 'neutral' zone.
	- Added table for ignition coil dwell
	- Added table(s) for Fuel Economy Gauge scaling factor
	- Added rear o2 sensor voltage limits
	- Added alternate ways to disable some common DTCs
	- Added AlphaN tables
	v0.45.1 - Fixed so AlphaN tables only open in CAL ID that supports it.
	v0.45.2 - Updated with AlphaN addresses for ID 41 & ID 60. Thanks liubchy.
	v0.45.3 - Fixed issue with Logger not working due to CAL ID mismatch.
	v0.45.4 - Added LTV support for ECU ID 1429861
	v0.45.5 - Added a couple of Anti-Jerk related tables
	v0.45.6	- Added IACV - AC Transient Adder
	v0.45.7 - Fixed formula for ECT/IAT Ignition Timing Compensation Multiplicative & Injector Pulsewidths (0.004 to 0.0053)
	v0.45.8 - Added Min/Max TPS Voltage Thresholds for DTC 12 (ID12)
	v0.45.9 - Added 3 IACV related tables for Cranking and solenoid characterization
	v0.45.10- Added DTC 214 Vehicle Speed Sensor table
	
	v0.46
	- Initial MS41.3 release
	12/16/20 - Changed formula for FF Ign. Trim to x-128 * (200/255)
	12/11/22 - Added MS41.3 Quad Load/MAF support

	 v0.46.2
	 - Added lm_min_diag: Minimum mass air threshold for MAF diagnostic path: short circuit to ground (MS41.0: 0x1BA)
	 - Added lm_max_diag: Maximum mass air threshold for MAF diagnostic path: short circuit to Ubat (MS41.0: 0x1B6)
	these will cause a MAF DTC to trigger and the ECU will fall back into MAF substitude (Alpha/N) map
	 
	In this BASE section define all the common table data and axis attributes.
	Leave out the ROM specific addresses. 	 
-->
	 
	<romid>
		<xmlid>BMWMS41BASE</xmlid>
		<internalidaddress>0000</internalidaddress>
		<internalidstring>00000000</internalidstring>
		<ecuid>00000000</ecuid>
		<year>1996-1999</year>
		<market>USDM</market>
		<make>BMW</make>
		<model>E36/E39/Z3</model>
		<submodel>MS41.0/MS41.1/MS41.2</submodel>
		<transmission>MT/AT</transmission>
	</romid>

<!--Control Bits-->
	<table type="2D" name="Byte 4" category="Control Bits" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Decimal Value" expression="x" to_byte="x"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="Convert from Decimal to Binary. Flip bits as needed. Then convert back to Decimal from Binary" sizey="1">
				<data>Byte 4</data>
			</table>
		<description>These are control bits for various functions. You will have to convert from Decimal to Binary (Windows Calc), flip the bits as needed, then convert it back to Decimal and enter that here.

	Bit # is from right to left starting at 0, up to 7. 

	Example: EWS Delete (Byte 8 Bit 7) for MS41.2
	Byte 8 = 00010110 (Decimal 22; 16h) - (STOCK)
	Byte 8 = 10010110 (Decimal 150; 96h) - (EWS DELETED)

	Read "Control Bits" thread at 
	www.romraider.com/forum/viewforum.php?f=42
		</description>
	</table>
	
	<table type="2D" name="Byte 5" category="Control Bits" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Decimal Value" expression="x" to_byte="x"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="Convert from Decimal to Binary. Flip bits as needed. Then convert back to Decimal from Binary" sizey="1">
				<data>Byte 5</data>
			</table>
		<description>These are control bits for various functions. You will have to convert from Decimal to Binary (Windows Calc), flip the bits as needed, then convert it back to Decimal and enter that here.

	Bit # is from right to left starting at 0, up to 7. 

	Example: EWS Delete (Byte 8 Bit 7) for MS41.2
	Byte 8 = 00010110 (Decimal 22; 16h) - (STOCK)
	Byte 8 = 10010110 (Decimal 150; 96h) - (EWS DELETED)

	Read "Control Bits" thread at 
	www.romraider.com/forum/viewforum.php?f=42
		</description>
	</table>
	
	<table type="Switch" name="Byte 6 - O2 Feedback" category="Control Bits" sizey="1" userlevel="1">
		<description>Select either 1 Channel or 2 Channel O2 Feedback. 1 Channel is generally used when a Turbo Manifold is installed.</description>
	</table>
	
	<table type="Switch" name="O2 Feedback Disable (Experimental)" category="Control Bits" sizey="1" userlevel="5">
		<state name="O2 Feedback - Enable" data="C" />
		<state name="O2 Feedback - Disable" data="11" />
		<description>To experiment with O2 Feedback Disable, you'll also have to modify "Byte 6 - O2 Feedback".</description>
	</table>

	<table type="2D" name="Byte 7" category="Control Bits" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Decimal Value" expression="x" to_byte="x"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="Convert from Decimal to Binary. Flip bits as needed. Then convert back to Decimal from Binary" sizey="1">
				<data>Byte 7</data>
			</table>
		<description>These are control bits for various functions. You will have to convert from Decimal to Binary (Windows Calc), flip the bits as needed, then convert it back to Decimal and enter that here.

	Bit # is from right to left starting at 0, up to 7. 

	Example: EWS Delete (Byte 8 Bit 7) for MS41.2
	Byte 8 = 00010110 (Decimal 22; 16h) - (STOCK)
	Byte 8 = 10010110 (Decimal 150; 96h) - (EWS DELETED)

	Read "Control Bits" thread at 
	www.romraider.com/forum/viewforum.php?f=42
		</description>
	</table>
	
	<table type="2D" name="Byte 8" category="Control Bits" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Decimal Value" expression="x" to_byte="x"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="Convert from Decimal to Binary. Flip bits as needed. Then convert back to Decimal from Binary" sizey="1">
				<data>Byte 8</data>
			</table>
		<description>These are control bits for various functions. You will have to convert from Decimal to Binary (Windows Calc), flip the bits as needed, then convert it back to Decimal and enter that here.

	Bit # is from right to left starting at 0, up to 7. 

	Example: EWS Delete (Byte 8 Bit 7) for MS41.2
	Byte 8 = 00010110 (Decimal 22; 16h) - (STOCK)
	Byte 8 = 10010110 (Decimal 150; 96h) - (EWS DELETED)

	Read "Control Bits" thread at 
	www.romraider.com/forum/viewforum.php?f=42
		</description>
	</table>

<!--Secondary Air Pump-->
	<table type="Switch" name="Secondary Air Pump - Logic" category="Secondary Air Pump" sizey="16" >
		<state name="Enabled"  data="01 00 01 00 01 00 01 00 01 00 01 00 01 00 01 00" />
		<state name="Disabled" data="FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF" />
		<description>Disable if the Secondary Air Pump has been removed.</description>
	</table>
	
	<table type="Switch" name="DTC 35 - Secondary Air Injection System Relay" category="Secondary Air Pump" sizey="1" >
		<state name="Enabled" data="02" />
		<state name="Disabled" data="00" />
		<description>Disable if the Secondary Air Pump System Relay has been removed.</description>
	</table>
	
	<table type="Switch" name="DTC 35 - Secondary Air Injection System Relay - Alternate" category="Secondary Air Pump" sizey="1" > x259
		<state name="Enabled" data="0A" />
		<state name="Disabled" data="00" />
		<description>Disable if the Secondary Air Pump System Relay has been removed.</description>
	</table>
	
	<table type="Switch" name="DTC 62 - Secondary Air Injection System Solenoid" category="Secondary Air Pump" sizey="1" >
		<state name="Enabled" data="02" />
		<state name="Disabled" data="00" />
		<description>Disable if the Secondary Air Pump Switching Valve/Solenoid has been removed.</description>
	</table>  
	
	<table type="Switch" name="DTC 62 - Secondary Air Injection System Solenoid - Alternate" category="Secondary Air Pump" sizey="1" > x25A
		<state name="Enabled" data="0A" />
		<state name="Disabled" data="00" />
		<description>Disable if the Secondary Air Pump Switching Valve/Solenoid has been removed.</description>
	</table>  

<!--Oxygen Sensors-->
	<table type="Switch" name="DTC 79,61 - Downstream O2 Sensor Heater (Bank 1,2)" category="Oxygen Sensors" sizey="1" userlevel="1">
		<state name="Enabled" data="02" />
		<state name="Disabled" data="00" />
	</table>
	
	<table type="Switch" name="DTC 79,61 - Downstream O2 Sensor Heater (Bank 1,2) - Alternate" category="Oxygen Sensors" sizey="1" userlevel="1"> x254
		<state name="Enabled" data="0A" />
		<state name="Disabled" data="00" />
		<description>Alternate method to disable Rear/Secondary/Downstream O2 DTCs if the normal method doesn't work.</description>
	</table>
	
	<table type="Switch" name="DTC 77,78 - Downstream O2 Sensor Voltage (Bank 1,2)" category="Oxygen Sensors" sizey="1" userlevel="1">
		<state name="Enabled" data="02" />
		<state name="Disabled" data="00" />
	</table>
	
	<table type="Switch" name="DTC 77,78 - Downstream O2 Sensor Voltage (Bank 1,2) - Alternate" category="Oxygen Sensors" sizey="1" userlevel="1"> x264
		<state name="Enabled" data="0A" />
		<state name="Disabled" data="00" />
	</table>
	
	<table type="Switch" name="DTC 233,234 - Catalytic Converter Overall Efficiency" category="Oxygen Sensors" sizey="1" userlevel="1"> x260
		<state name="Enabled" data="01" />
		<state name="Disabled" data="00" />
	</table>
	
	<table type="2D" name="DTC 233,234 - Catalytic Converter Overall Efficiency - Downstream O2 Sensor Minimum Voltage" category="Oxygen Sensors" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Volts" expression="x*.0195" to_byte="x/.0195"  format="0.00" fineincrement="0.1" coarseincrement="10" />
			<table type="Static Y Axis" name="Set to 0V if using Downstream O2 as a sensor input" sizey="1">
				<data>Minimum Allowable Volts</data>
			</table>
		<description>This is the minimum voltage the rear O2 input will accept before throwing a code. Setting this to 0v is useful when wanting to use the rear O2 input to log a wideband O2.</description>
	</table> 
	
	<table type="2D" name="DTC 233,234 - Catalytic Converter Overall Efficiency - Downstream O2 Sensor Maximum Voltage" category="Oxygen Sensors" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Volts" expression="x*.0195" to_byte="x/.0195"  format="0.00" fineincrement="0.1" coarseincrement="10" />
			<table type="Static Y Axis" name="Set to 5V if using Downstream O2 as a sensor input" sizey="1">
				<data>Maximum Allowable Volts</data>
			</table>
		<description>This is the maximum voltage the rear O2 input will accept before throwing a code. Setting this to 5v is useful when wanting to use the rear O2 input to log a wideband O2.</description>
	</table> 
	
	<table type="2D" name="DTC 233,234 - Catalytic Converter Overall Efficiency - Downstream O2 Maximum Range" category="Oxygen Sensors" storagetype="uint16" endian="little" sizey="1" userlevel="1">
		<scaling units="???" expression="x" to_byte="x"  format="0" fineincrement="100" coarseincrement="10000" />
			<table type="Static Y Axis" name="Set to 65535 if using Downstream O2 as a sensor input" sizey="1">
				<data>binary word</data>
			</table>
		<description>This is the range for the rear O2 input will accept before throwing a code. Maxing both these out (255) is useful when wanting to use the rear O2 input to log a wideband O2.</description>
	</table>
	
	<table type="2D" name="Downstream O2 Sensor Minimum Voltage" category="Oxygen Sensors" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Volts" expression="x*.0195" to_byte="x/.0195"  format="0.00" fineincrement="0.1" coarseincrement="10" />
			<table type="Static Y Axis" name="Set to 0V if using Downstream O2 as a sensor input" sizey="1">
				<data>Minimum Allowable Volts</data>
			</table>
		<description>This is the minimum voltage the rear O2 input will accept before throwing a code. Setting this to 0v is useful when wanting to use the rear O2 input to log a wideband O2.</description>
	</table> 
	
	<table type="2D" name="Downstream O2 Sensor Maximum Voltage" category="Oxygen Sensors" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Volts" expression="x*.0195" to_byte="x/.0195"  format="0.00" fineincrement="0.1" coarseincrement="10" />
			<table type="Static Y Axis" name="Set to 5V if using Downstream O2 as a sensor input" sizey="1">
				<data>Maximum Allowable Volts</data>
			</table>
		<description>This is the range for the rear O2 input will accept before throwing a code. Maxing both these out (255) is useful when wanting to use the rear O2 input to log a wideband O2.</description>
	</table> 
	
	<table type="Switch" name="DTC 25,55 - Upstream O2 Sensor Heater (Bank 1,2)" category="Oxygen Sensors" sizey="1" userlevel="4">
		<state name="Enabled" data="02" />
		<state name="Disabled" data="00" />
	</table>
	
	<table type="Switch" name="DTC 25,55 - Upstream O2 Sensor Heater (Bank 1,2) - Alternate" category="Oxygen Sensors" sizey="1" userlevel="4"> x253
		<state name="Enabled" data="0A" />
		<state name="Disabled" data="00" />
	</table>
	
	<table type="2D" name="Upstream O2 Sensor Heater Minimum Voltage" category="Oxygen Sensors" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Volts" expression="x*.0195" to_byte="x/.0195"  format="0.00" fineincrement="0.1" coarseincrement="10" />
			<table type="Static Y Axis" name="Set to 0V if using Upstream O2 as a sensor input" sizey="1">
				<data>Minimum Allowable Volts</data>
			</table>
		<description>Setting this to 0v may be useful when wanting to use the front O2 input to run a wideband O2.</description>
	</table> 
	
	<table type="2D" name="Upstream O2 Sensor Heater Maximum Voltage" category="Oxygen Sensors" storagetype="uint8" sizey="1" userlevel="1">
		<scaling units="Volts" expression="x*.0195" to_byte="x/.0195"  format="0.00" fineincrement="0.1" coarseincrement="10" />
			<table type="Static Y Axis" name="Set to 5V if using Upstream O2 as a sensor input" sizey="1">
				<data>Maximum Allowable Volts</data>
			</table>
		<description>Setting this to 5v may be useful when wanting to use the front O2 input to run a wideband O2.</description>
	</table>
	
	<table type="Switch" name="DTC 75,76 - Upstream O2 Sensor Voltage (Bank 1,2)" category="Oxygen Sensors" sizey="1" userlevel="4">
		<state name="Enabled" data="02" />
		<state name="Disabled" data="00" />
		<description>LBD_HEAT_MAX_VOLTS_0387, LBD_HEAT_MIN_VOLTS_0389</description>
	</table>
	
	<table type="Switch" name="DTC 75,76 - Upstream O2 Sensor Voltage (Bank 1,2) - Alternate" category="Oxygen Sensors" sizey="1" userlevel="4"> x263
		<state name="Enabled" data="0A" />
		<state name="Disabled" data="00" />
		<description>LBD_HEAT_MAX_VOLTS_0387, LBD_HEAT_MIN_VOLTS_0389</description>
	</table>
	
	<table type="2D" name="DTC 200, 201 - Lambda Regulation (Upstream) - Voltage Difference XXX" category="Oxygen Sensors" storagetype="uint8"  userlevel="1" sizey="1" >
		<scaling units="Voltage" expression="x*(5/255)" to_byte="x/(5/255)" format="0.00" fineincrement=".01" coarseincrement=".1" />
			<table type="Static Y Axis" name=" " sizey="1">
				<data>Oxygen Sensor Voltage Difference</data>
			</table>
		<description>TESTING REQUIRED - If a voltage difference during Lambda Regulation is less than this value, ECU might think there is a problem. Reduce this value for O2 sensors that don't change their voltage much due to age.</description>
	</table>

<!--Catalyst Heating-->
	<table type="2D" name="CH - On/Off - VANOS" category="Catalyst Heating" storagetype="uint8" sizey="8" userlevel="1">
		<scaling units="On/Off" expression="x" to_byte="x"  format="0" fineincrement="1" coarseincrement="1" />
			<table type="Y Axis" name="Coolant Temperature @ Engine Start" storagetype="uint8">
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>A value of 1 activates VANOS during a cold start to get more air to aid Catalyst Heating. It can sometimes cause a rough cold start. Set this to 0 to disable.</description>
	</table>
	
	<table type="2D" name="CH - Duration - Idle Speed Target Increase" category="Catalyst Heating" storagetype="uint16" endian="little" sizey="8" userlevel="1">
		<scaling units="seconds" expression="x*.1" to_byte="x/.1"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Y Axis" name="Coolant Temperature @ Engine Start" storagetype="uint8">
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This table determines the duration after engine start for an increased Idle Speed Target that is part of the Catalyst Heating function.</description>
	</table>
	
	<table type="2D" name="CH - Duration - Ignition Retard" category="Catalyst Heating" storagetype="uint16" endian="little" sizey="8" userlevel="1">
		<scaling units="seconds" expression="x*.1" to_byte="x/.1"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Y Axis" name="Coolant Temperature @ Engine Start" storagetype="uint8">
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This table determines the duration after engine start for retarded Ignition Timing that is part of the Catalyst Heating function. Disabling this also disables the "Fuel Enrichment" part of the Catalyst Heating function.</description>
	</table>
	
	<table type="2D" name="CH - Duration - Fuel Enrichment" category="Catalyst Heating" storagetype="uint16" endian="little" sizey="8" userlevel="1">
		<scaling units="seconds" expression="x*.1" to_byte="x/.1"  format="0" fineincrement="1" coarseincrement="10" />
			<table type="Y Axis" name="Coolant Temperature @ Engine Start" storagetype="uint8">
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>This table determines the duration after engine start for enriched Fueling that is part of the Catalyst Heating function.</description>
	</table>
	
	<table type="2D" name="CH - Fuel Enrichment - Multiplicative (Idle)" category="Catalyst Heating" storagetype="uint8"  userlevel="3" sizey="8" >
		<scaling units="%" expression="x*.785" to_byte="x/.785" format="0" fineincrement="1" coarseincrement="5" />
			<table type="Y Axis" name="Coolant Temperature" storagetype="uint8" logparam="P2" >
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>Multiply this table to "CH - Fuel Enrichment - Nominal" and add "CH - Fuel Enrichment - Additive Value" to calculate Fuel Enrichment % when the Catalyst Heating function is enabled. This table is only used during idle.</description>
	</table>
	
	<table type="2D" name="CH - Fuel Enrichment - Multiplicative (above Idle)" category="Catalyst Heating" storagetype="uint8"  userlevel="3" sizey="8" >
		<scaling units="%" expression="x*.785" to_byte="x/.785" format="0" fineincrement="1" coarseincrement="5" />
			<table type="Y Axis" name="Coolant Temperature" storagetype="uint8" logparam="P2">
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>Multiply this table to "CH - Fuel Enrichment - Nominal" and add "CH - Fuel Enrichment - Additive Value" to calculate Fuel Enrichment % when the Catalyst Heating function is enabled. This table is only used above Idle.</description>
	</table>
	
	<table type="3D" name="CH - Fuel Enrichment - Nominal" category="Catalyst Heating" storagetype="uint8"  userlevel="3" sizex="8" sizey="8" >
		<scaling units="%" expression="x*(100/255)" to_byte="x/(100/255)" format="0" fineincrement="1" coarseincrement="5" />
			<table type="X Axis" name="Load" storagetype="uint8" logparam="E2">
				<scaling units="mg/stroke [Limit = 1389]" expression="x*(1389/255)" to_byte="x/(1389/255)" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" logparam="P8">
				<scaling units="RPM" expression="x*32" to_byte="x/32" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>Multiply this table to "CH - Fuel Enrichment - Multiplicative (Idle)" or "CH - Fuel Enrichment - Multiplicative (above Idle)" and add "CH - Fuel Enrichment - Additive" to calculate Fuel Enrichment % when the Catalyst Heating function is enabled.</description>
	</table>
	
	<table type="3D" name="CH - Fuel Enrichment - Additive" category="Catalyst Heating" storagetype="uint16" endian="little"  userlevel="3" sizey="8" sizex="8" >
		<scaling units="%" expression="(x-2048)*.0244" to_byte="x/.0244+2048" format="0" fineincrement="1" coarseincrement="5" />
			<table type="X Axis" name="Counter since Engine Start" storagetype="uint16" endian="little">
				<scaling units="Time" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Coolant Temperature" storagetype="uint8" logparam="P2">
				<scaling units="&deg;C" expression="x*.75-48" to_byte="(x+48)/.75" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>Add the values in this table after multiplying "CH - Fuel Enrichment - Nominal" to either "CH - Fuel Enrichment - Multiplicative (Idle)" or "CH - Fuel Enrichment - Multiplicative (above Idle)" to calculate Fuel Enrichment % when the Catalyst Heating function is enabled.</description>
	</table>

<!--Catalyst Overheating Protection-->
	<table type="3D" name="COP - Fuel Enrichment - Nominal" category="Catalyst Overheating Protection" storagetype="uint8"  userlevel="1" sizex="6" sizey="6" >
		<scaling units="%" expression="x*(100/255)" to_byte="x/(100/255)" format="0" fineincrement="5" coarseincrement="50" />
			<table type="X Axis" name="Load" storagetype="uint8" logparam="E2" >
				<scaling units="mg/stroke [Limit = 1389]" expression="x*(1389/255)" to_byte="x/(1389/255)" format="0" fineincrement="5" coarseincrement="50" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" logparam="P8" >
				<scaling units="RPM" expression="x*32" to_byte="x/32" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>IP_TI_COP__N_32__MAF - This table is added to "COP - Fuel Enrichment - Additive" to determine final Fuel Enrichment due to COP. The code will not allow any negative Fuel Enrichment so setting this table to all 0 will disable all Catalyst Overheating Protection. Only do this if there is no Catalytic Converter present.</description>
	</table>
	
	<table type="2D" name="COP - Fuel Enrichment - Additive" category="Catalyst Overheating Protection" storagetype="uint8"  userlevel="3" sizey="4" >
		<scaling units="%" expression="(x-128)*(100/255)" to_byte="x/(100/255)+128" format="0" fineincrement="5" coarseincrement="50" />
			<table type="Y Axis" name="Ignition Correction (Knock + ECT/IAT Compensation)" storagetype="uint8">
				<scaling units="&deg;CRK" expression="(x-128)*.375" to_byte="x/.375+128" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>IP_TI_COP_IGA__IGA_COP - This table is added to "COP - Fuel Enrichment - Nominal" to determine final Fuel Enrichment due to COP. The code will not allow any negative Fuel Enrichment so if the values in "COP - Fuel Enrichment - Nominal" are already 0, this table will not reduce the values any further.</description>
	</table>
	
	<table type="2D" name="COP - Fuel Enrichment - Step Size" category="Catalyst Overheating Protection" storagetype="uint8"  userlevel="3" sizey="1" >
		<scaling units="%" expression="(x)*(100/255)" to_byte="x/(100/255)" format="0.0" fineincrement="1" coarseincrement="10" />
			<table type="Static Y Axis" name="Fuel Enrichment - Increment/Decrement" sizey="1">
				<data></data>
			</table>
		<description>C_TI_COP_INC - This value limits how quickly the calculated Fuel Enrichment due to COP is allowed to change in both the positive and negative direction to prevent sudden changes to the AFR.</description>
	</table>
	
	<table type="3D" name="COP - Minimum Load" category="Catalyst Overheating Protection" storagetype="uint8"  userlevel="3" sizex="4" sizey="6" >
		<scaling units="mg/stroke [Limit = 1389]" expression="x*(1389/255)" to_byte="x/(1389/255)" format="0" fineincrement="5" coarseincrement="50" />
			<table type="X Axis" name="Ignition Correction (Knock + ECT/IAT Compensation)" storagetype="uint8">
				<scaling units="&deg;CRK" expression="(x-128)*.375" to_byte="x/.375+128" format="0" fineincrement="1" coarseincrement="10" />
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" logparam="P8">
				<scaling units="RPM" expression="x*32" to_byte="x/32" format="0" fineincrement="1" coarseincrement="10" />
			</table>
		<description>IP_MAF_MIN_COP__N_32__IGA_COP - This table sets the minimum Load for COP to be active. Setting these values to max will disable Fuel Enrichment due to COP.</description>
	</table>
	
	<table type="2D" name="COP - Minimum Load Hystersis" category="Catalyst Overheating Protection" storagetype="uint8"  userlevel="3" sizey="1" >
		<scaling units="mg/stroke [Limit = 1389]" expression="x*(1389/255)" to_byte="x/(1389/255)" format="0" fineincrement="5" coarseincrement="50" />
			<table type="Static Y Axis" name="Minimum Load Hystersis" sizey="1">
				<data></data>
			</table>
		<description>C_MAF_MIN_HYS_COP - Hysteresis for Minimum Load threshold for COP.</description>
	</table>
	
	<table type="2D" name="COP - Minimum Ignition Correction" category="Catalyst Overheating Protection" storagetype="uint8"  userlevel="3" sizey="1" >
		<scaling units="&deg;CRK" expression="(x-128)*(.375)" to_byte="x/(.375)+128" format="0" fineincrement=".5" coarseincrement="5" />
			<table type="Static Y Axis" name="Minimum Ignition Correction" sizey="1">
				<data></data>
			</table>
		<description>C_IGA_MIN_COP - This value determines the minimum Ignition Correction for COP to be active. COP will only be active Ignition Correction due to Knock and ECT/IAT Compensations are less than 0 as set in the stock tune.</description>
	</table>

<!--Adaptive Fuel Learning-->
	<table type="2D" name="Lambda Integrator - Minimum Limit" category="Adaptive Fuel Learning" storagetype="uint16" endian="little"  userlevel="1" sizey="1">
		<scaling units="%" expression="(x-32768)*(100/65535)" to_byte="(x/(100/65535))+32768" format="0.00" fineincrement=".1" coarseincrement="1" />
			<table type="Static Y Axis" name="Lambda Integrator - Minimum Limit" sizey="1">